name: Combine MDX Files

on:
  push:
    branches:
      - main

jobs:
  combine-mdx-files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Combine .mdx files
        run: |
          find . -type f -name "*.mdx" -not -path "*/ko/*" \
            -exec sh -c '
              perl -0777 -ne '\''
                if (/^---\n.*?title: (.*?)[\n].*?---\n(.*)/s) {
                  print "# $1\n$2\n\n";
                }
              '\'' "$1"
            ' sh {} \; > combined.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add combined.md
          git commit -m "Update combined.md [skip ci]" || echo "No changes to commit"
          git push "https://${{ secrets.PAT_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" main
